backend:
  name: git-gateway

media_folder:  "static/img" # Folder where user uploaded files should go
public_folder: "img"

# A list of collections the CMS should be able to edit
collections:
  - name:   "about"
    label:  "About"
    folder: "content/about"
    create: true
    fields:
      - { label: "Draft",        name: "draft",    widget: "boolean", default: false }
      - { label: "Title",        name: "title",    widget: "string"   }
      - { label: "Rank",         name: "rank",     widget: "number",  valueType: "int", min: 1 }
      - { label: "Body",         name: "body",     widget: "markdown" }
  - name:   "project"
    label:  "Project"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Draft",        name: "draft",    widget: "boolean", default: false }
      - { label: "Title",        name: "title",    widget: "string"   }
      - { label: "Project Date", name: "date",     widget: "date",    dateFormat: "DD-MM-YYYY", timeFormat: false }
      - { label: "Featured",     name: "featured", widget: "boolean", default: false }
      - { label: "Image",        name: "image",    widget: "image"    }
      - { label: "Body",         name: "body",     widget: "markdown" }
  - name:   "blog_post"
    label:  "Blog Post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Draft",        name: "draft",    widget: "boolean", default: false }
      - { label: "Title",        name: "title",    widget: "string"   }
      - { label: "Publish Date", name: "date",     widget: "date"     }
      - { label: "Featured",     name: "featured", widget: "boolean", default: false }
      - { label: "Body",         name: "body",     widget: "markdown" }
  - name: "software"
    label: "Software"
    folder: "content/software"
    create: true
    fields:
      - { label: "Draft",        name: "draft",    widget: "boolean", default: false }
      - { label: "Title",        name: "title",    widget: "string"   }
      - { label: "Publish Date", name: "date",     widget: "date"     }
      - { label: "Image",        name: "image",    widget: "image",   required: false }
      - { label: "Featured",     name: "featured", widget: "boolean", default: false }
      - { label: "Body",         name: "body",     widget: "markdown" }